text-board/config/routes.rb
Rails.application.routes.draw do
  root to: 'texts#index'
  resources :texts
end

text-board/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

text-board/app/models/text.rb
class Text < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: {maximum: 255}
end

text-board/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

text-board/app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text,only: [:show, :edit, :update, :destroy]

  def index
    @texts = Text.all.page(params[:page])
  end
  
  def show
  end
  
  def new
    @text = Text.new
  end
  
  def create
    @text = Text.new(text_params)
    
    if @text.save
      flash[:success] = 'Textが正常に投稿されました'
      redirect_to @text
    else
      flash.now[:danger] = 'Textが投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update

    if @text.update(text_params)
      flash[:success] = 'Text は正常に更新されました'
      redirect_to @text
    else
      flash.now[:danger] = 'Text は更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @text.destroy

    flash[:success] = 'Text は正常に削除されました'
    redirect_to texts_url
  end
  
  private
  
  def text_params
    params.require(:text).permit(:content, :title)
  end
  
  def set_text
    @text = Text.find(params[:id])
  end
  
    
end

text-board/app/helpers/application_helper.rb
module ApplicationHelper
end

text-board/app/helpers/texts_helper.rb
module TextsHelper
end

text-board/app/views/layouts/_flash_texts.html.erb
<% flash.each do |text_type,text| %>
  <div class="alert alert-<%= text_type %>"><%= text %></div>
<% end %>

text-board/app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false>
          <span class="sr-only">Toggle navigation></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TextBoard</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to '新規テキストの投稿',new_text_path %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

text-board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <title>TextBoard</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_texts' %>
      
      <%= yield %>
    </div>
  </body>
</html>